import { palette } from '../theme/palette';
import { modelAssets } from './assets';
import type { CatalogItem } from './types';

export const catalog: readonly CatalogItem[] = [
  {
    id: 'masjid-model',
    name: 'Masjid Model',
    category: 'Buildings',
    asset: modelAssets.masjid,
    allowedSurfaces: ['floor'],
    footprint: { width: 2, depth: 2 },
    modelScale: 0.76,
    placeholderColor: palette.mutedTeal,
  },
  {
    id: 'fanous-lantern',
    name: 'Fanous Lantern',
    category: 'Lights',
    asset: modelAssets.fanousLantern,
    allowedSurfaces: ['floor'],
    footprint: { width: 1, depth: 1 },
    modelScale: 0.39,
    placeholderColor: palette.gold,
    emitsLight: true,
  },
  {
    id: 'tasbih',
    name: 'Tasbih',
    category: 'Prayer',
    asset: modelAssets.tasbih,
    allowedSurfaces: ['floor'],
    footprint: { width: 1, depth: 1 },
    modelScale: 0.3,
    placeholderColor: '#7EA48E',
  },
  {
    id: 'rehal-quran',
    name: 'Quran & Rehal',
    category: 'Prayer',
    asset: modelAssets.rehalQuran,
    allowedSurfaces: ['floor'],
    footprint: { width: 1, depth: 1 },
    modelScale: 0.39,
    placeholderColor: palette.terracotta,
  },
  {
    id: 'minbar',
    name: 'Minbar',
    category: 'Prayer',
    asset: modelAssets.minbar,
    allowedSurfaces: ['floor'],
    footprint: { width: 2, depth: 2 },
    modelScale: 0.67,
    placeholderColor: '#9A6748',
  },
  {
    id: 'floor-cushion',
    name: 'Floor Cushion',
    category: 'Seating',
    asset: modelAssets.floorCushion,
    allowedSurfaces: ['floor'],
    footprint: { width: 1, depth: 1 },
    modelScale: 0.39,
    placeholderColor: '#D98D74',
  },
  {
    id: 'curtains',
    name: 'Arch Curtains',
    category: 'Wall',
    asset: modelAssets.curtains,
    allowedSurfaces: ['wallL', 'wallR'],
    footprint: { width: 2, depth: 1 },
    wallFootprint: { width: 3, height: 2 },
    modelScale: 0.59,
    placeholderColor: '#DDBE83',
    rotatable: false,
  },
  {
    id: 'minaret',
    name: 'Mini Minaret',
    category: 'Buildings',
    asset: modelAssets.minaret,
    allowedSurfaces: ['floor'],
    footprint: { width: 1, depth: 1 },
    modelScale: 0.52,
    placeholderColor: '#94B7AE',
  },
  {
    id: 'wall-art',
    name: 'Islamic Wall Art',
    category: 'Wall',
    asset: modelAssets.wallArt,
    allowedSurfaces: ['wallL', 'wallR'],
    footprint: { width: 1, depth: 1 },
    wallFootprint: { width: 2, height: 2 },
    modelScale: 0.4,
    placeholderColor: '#CFAE66',
    rotatable: false,
  },
  {
    id: 'mini-masjid',
    name: 'Mini Masjid Model',
    category: 'Decor',
    asset: modelAssets.miniMasjid,
    allowedSurfaces: ['floor'],
    footprint: { width: 2, depth: 2 },
    modelScale: 0.46,
    placeholderColor: '#8CB9AA',
  },
] as const;

export const catalogById = Object.fromEntries(catalog.map((item) => [item.id, item])) as Record<string, CatalogItem>;
