import { palette } from '../theme/palette';
import { importedModelAssets, modelAssets } from './assets';
import type { CatalogItem } from './types';

const importedPlaceholderColors = [
  palette.mutedTeal,
  palette.gold,
  palette.terracotta,
  '#7EA48E',
  '#D98D74',
  '#94B7AE',
] as const;

const importedCatalogItems: readonly CatalogItem[] = importedModelAssets.map((model, index) => ({
  id: model.id,
  name: model.name,
  category: 'New',
  asset: model.asset,
  allowedSurfaces: ['floor'],
  footprint: { width: 2, depth: 2 },
  modelScale: 0.48,
  placeholderColor: importedPlaceholderColors[index % importedPlaceholderColors.length],
}));

export const catalog: readonly CatalogItem[] = [
  ...importedCatalogItems,
  {
    id: 'masjid-model',
    name: 'Prayer Rug',
    category: 'Prayer',
    asset: modelAssets.masjid,
    allowedSurfaces: ['floor'],
    footprint: { width: 2, depth: 2 },
    modelScale: 0.76,
    placeholderColor: palette.mutedTeal,
  },
  {
    id: 'fanous-lantern',
    name: 'Fanous Lantern',
    category: 'Lights',
    asset: modelAssets.fanousLantern,
    allowedSurfaces: ['floor'],
    footprint: { width: 1, depth: 1 },
    modelScale: 0.39,
    placeholderColor: palette.gold,
    emitsLight: true,
  },
  {
    id: 'tasbih',
    name: 'Open Quran & Rehal',
    category: 'Prayer',
    asset: modelAssets.tasbih,
    allowedSurfaces: ['floor'],
    footprint: { width: 1, depth: 1 },
    modelScale: 0.3,
    placeholderColor: '#7EA48E',
  },
  {
    id: 'rehal-quran',
    name: 'Quran & Rehal',
    category: 'Prayer',
    asset: modelAssets.rehalQuran,
    allowedSurfaces: ['floor'],
    footprint: { width: 1, depth: 1 },
    modelScale: 0.39,
    placeholderColor: palette.terracotta,
  },
  {
    id: 'minbar',
    name: 'Minbar',
    category: 'Prayer',
    asset: modelAssets.minbar,
    allowedSurfaces: ['floor'],
    footprint: { width: 2, depth: 2 },
    modelScale: 0.67,
    placeholderColor: '#9A6748',
  },
  {
    id: 'floor-cushion',
    name: 'Floor Cushion',
    category: 'Seating',
    asset: modelAssets.floorCushion,
    allowedSurfaces: ['floor'],
    footprint: { width: 1, depth: 1 },
    modelScale: 0.39,
    placeholderColor: '#D98D74',
  },
  {
    id: 'curtains',
    name: 'Star Wall Lantern',
    category: 'Lights',
    asset: modelAssets.curtains,
    allowedSurfaces: ['wallL', 'wallR'],
    footprint: { width: 2, depth: 1 },
    wallFootprint: { width: 3, height: 2 },
    modelScale: 0.59,
    placeholderColor: '#DDBE83',
    rotatable: false,
  },
  {
    id: 'minaret',
    name: 'Globe Fanous Lantern',
    category: 'Lights',
    asset: modelAssets.minaret,
    allowedSurfaces: ['floor'],
    footprint: { width: 1, depth: 1 },
    modelScale: 0.52,
    placeholderColor: '#94B7AE',
  },
  {
    id: 'wall-art',
    name: 'Quran Wall Display',
    category: 'Wall',
    asset: modelAssets.wallArt,
    allowedSurfaces: ['wallL', 'wallR'],
    footprint: { width: 1, depth: 1 },
    wallFootprint: { width: 2, height: 2 },
    modelScale: 0.4,
    placeholderColor: '#CFAE66',
    rotatable: false,
  },
  {
    id: 'tasbih-crescent-hook',
    name: 'Crescent Tasbih Hook',
    category: 'Wall',
    proceduralModel: 'tasbih-crescent-hook',
    allowedSurfaces: ['wallL', 'wallR'],
    footprint: { width: 1, depth: 1 },
    wallFootprint: { width: 1, height: 2 },
    modelScale: 1,
    placeholderColor: palette.gold,
    rotatable: false,
  },
  {
    id: 'tasbih-mihrab-rack',
    name: 'Mihrab Tasbih Rack',
    category: 'Wall',
    proceduralModel: 'tasbih-mihrab-rack',
    allowedSurfaces: ['wallL', 'wallR'],
    footprint: { width: 2, depth: 1 },
    wallFootprint: { width: 2, height: 2 },
    modelScale: 1,
    placeholderColor: palette.terracotta,
    rotatable: false,
  },
  {
    id: 'tasbih-geometric-rail',
    name: 'Geometric Tasbih Rail',
    category: 'Wall',
    proceduralModel: 'tasbih-geometric-rail',
    allowedSurfaces: ['wallL', 'wallR'],
    footprint: { width: 3, depth: 1 },
    wallFootprint: { width: 3, height: 2 },
    modelScale: 1,
    placeholderColor: palette.mutedTeal,
    rotatable: false,
  },
  {
    id: 'tasbih-mashrabiya-board',
    name: 'Mashrabiya Tasbih Board',
    category: 'Wall',
    proceduralModel: 'tasbih-mashrabiya-board',
    allowedSurfaces: ['wallL', 'wallR'],
    footprint: { width: 2, depth: 1 },
    wallFootprint: { width: 2, height: 2 },
    modelScale: 1,
    placeholderColor: '#8F6A50',
    rotatable: false,
  },
  {
    id: 'tasbih-palm-hanger',
    name: 'Palm Tasbih Hanger',
    category: 'Wall',
    proceduralModel: 'tasbih-palm-hanger',
    allowedSurfaces: ['wallL', 'wallR'],
    footprint: { width: 3, depth: 1 },
    wallFootprint: { width: 3, height: 2 },
    modelScale: 1,
    placeholderColor: '#7EA48E',
    rotatable: false,
  },
  {
    id: 'mini-masjid',
    name: 'Mini Masjid Room',
    category: 'Decor',
    asset: modelAssets.miniMasjid,
    allowedSurfaces: ['floor'],
    footprint: { width: 2, depth: 2 },
    modelScale: 0.46,
    placeholderColor: '#8CB9AA',
  },
] as const;

export const catalogById = Object.fromEntries(catalog.map((item) => [item.id, item])) as Record<string, CatalogItem>;
