export const catalogThumbnails: Readonly<Record<string, number>> = {
  'masjid-model': require('../../assets/catalog-thumbnails/masjid-model.png'),
  'fanous-lantern': require('../../assets/catalog-thumbnails/fanous-lantern.png'),
  tasbih: require('../../assets/catalog-thumbnails/tasbih.png'),
  'rehal-quran': require('../../assets/catalog-thumbnails/rehal-quran.png'),
  minbar: require('../../assets/catalog-thumbnails/minbar.png'),
  'floor-cushion': require('../../assets/catalog-thumbnails/floor-cushion.png'),
  curtains: require('../../assets/catalog-thumbnails/curtains.png'),
  minaret: require('../../assets/catalog-thumbnails/minaret.png'),
  'wall-art': require('../../assets/catalog-thumbnails/wall-art.png'),
  'tasbih-crescent-hook': require('../../assets/catalog-thumbnails/tasbih-crescent-hook.png'),
  'tasbih-mihrab-rack': require('../../assets/catalog-thumbnails/tasbih-mihrab-rack.png'),
  'tasbih-geometric-rail': require('../../assets/catalog-thumbnails/tasbih-geometric-rail.png'),
  'tasbih-mashrabiya-board': require('../../assets/catalog-thumbnails/tasbih-mashrabiya-board.png'),
  'tasbih-palm-hanger': require('../../assets/catalog-thumbnails/tasbih-palm-hanger.png'),
  'mini-masjid': require('../../assets/catalog-thumbnails/mini-masjid.png'),
  'imported-model-01': require('../../assets/catalog-thumbnails/characters/pose-03-qiyam.png'),
  'imported-model-02': require('../../assets/catalog-thumbnails/characters/pose-02-takbir.png'),
  'imported-model-03': require('../../assets/catalog-thumbnails/characters/pose-06-jalsa.png'),
  'imported-model-04': require('../../assets/catalog-thumbnails/characters/pose-01-a-pose.png'),
  'imported-model-06': require('../../assets/catalog-thumbnails/characters/pose-04-ruku.png'),
  'imported-model-07': require('../../assets/catalog-thumbnails/characters/pose-07-taslim.png'),
  'imported-model-08': require('../../assets/catalog-thumbnails/characters/pose-08-dua.png'),
  'imported-model-09': require('../../assets/catalog-thumbnails/characters/pose-05-sujud.png'),
  'imported-model-10': require('../../assets/catalog-thumbnails/storage/bookshelf-low.png'),
  'imported-model-11': require('../../assets/catalog-thumbnails/plants/hanging-planter-ivy.png'),
  'imported-model-12': require('../../assets/catalog-thumbnails/plants/succulent-bowl.png'),
  'imported-model-13': require('../../assets/catalog-thumbnails/storage/bookcase-tall.png'),
  'imported-model-14': require('../../assets/catalog-thumbnails/storage/quran-chest.png'),
  'imported-model-15': require(
    '../../assets/catalog-thumbnails/plants/hanging-planter-macrame.png',
  ),
  'imported-model-16': require('../../assets/catalog-thumbnails/plants/olive-tree-potted.png'),
  'imported-model-17': require('../../assets/catalog-thumbnails/plants/date-palm-potted.png'),
  'imported-model-18': require('../../assets/catalog-thumbnails/storage/cabinet-with-books.png'),
  'imported-model-19': require(
    '../../assets/catalog-thumbnails/characters/blank-face-thobe-toy-figure.png',
  ),
  'imported-model-20': require('../../assets/catalog-thumbnails/storage/wall-shelf-books.png'),
  'imported-model-21': require('../../assets/catalog-thumbnails/pets/cat-sitting-cream.png'),
  'imported-model-22': require('../../assets/catalog-thumbnails/pets/cat-lying-grey.png'),
  'imported-model-23': require(
    '../../assets/catalog-thumbnails/tables/side-table-terracotta.png',
  ),
  'imported-model-24': require('../../assets/catalog-thumbnails/pets/cat-kitten-orange.png'),
  'imported-model-25': require(
    '../../assets/catalog-thumbnails/tables/tray-table-octagonal.png',
  ),
  'imported-model-26': require('../../assets/catalog-thumbnails/tables/tea-table-round.png'),
  'imported-model-27': require('../../assets/catalog-thumbnails/tables/majlis-table-low.png'),
  'imported-model-28': require('../../assets/catalog-thumbnails/pets/cat-sleeping-ginger.png'),
  'imported-model-37': require('../../assets/catalog-thumbnails/decor/bakhoor-burner-cube.png'),
  'imported-model-38': require(
    '../../assets/catalog-thumbnails/storage/two-tier-wooden-shoe-rack.png',
  ),
  'imported-model-39': require('../../assets/catalog-thumbnails/lights/wall-sconce.png'),
  'imported-model-40': require('../../assets/catalog-thumbnails/lights/floor-lamp.png'),
  'imported-model-41': require('../../assets/catalog-thumbnails/decor/bakhoor-burner-round.png'),
  'imported-model-42': require('../../assets/catalog-thumbnails/lights/candle-holder.png'),
  'imported-model-43': require('../../assets/catalog-thumbnails/lights/chandelier-mosque.png'),
  'imported-model-44': require('../../assets/catalog-thumbnails/lights/ceiling-lamp-dome.png'),
  'imported-model-45': require('../../assets/catalog-thumbnails/serving/dallah-tray-set.png'),
  'imported-model-46': require('../../assets/catalog-thumbnails/decor/cream-slippers-pair.png'),
  'imported-model-47': require('../../assets/catalog-thumbnails/serving/dallah-pot-gold-01.png'),
  'imported-model-48': require('../../assets/catalog-thumbnails/serving/dallah-pot-copper.png'),
  'imported-model-49': require(
    '../../assets/catalog-thumbnails/lights/lantern-string-lights.png',
  ),
  'imported-model-50': require('../../assets/catalog-thumbnails/decor/attar-bottle-gold.png'),
  'imported-model-51': require('../../assets/catalog-thumbnails/serving/dates-bowl.png'),
  'imported-model-52': require('../../assets/catalog-thumbnails/decor/eid-gift-boxes.png'),
  'imported-model-53': require('../../assets/catalog-thumbnails/wall/prayer-times-clock.png'),
  'imported-model-54': require('../../assets/catalog-thumbnails/serving/iftar-tray.png'),
  'imported-model-55': require('../../assets/catalog-thumbnails/wall/crescent-moon-wall.png'),
  'imported-model-56': require('../../assets/catalog-thumbnails/serving/dallah-pot-gold-02.png'),
  'imported-model-57': require('../../assets/catalog-thumbnails/seating/bolster-cushion.png'),
  'imported-model-58': require(
    '../../assets/catalog-thumbnails/decor/crescent-moon-ornament.png',
  ),
  'imported-model-59': require('../../assets/catalog-thumbnails/wall/mashrabiya-panel.png'),
  'imported-model-60': require('../../assets/catalog-thumbnails/rugs/round-rug-spiral.png'),
  'imported-model-61': require('../../assets/catalog-thumbnails/wall/oval-mirror.png'),
  'imported-model-62': require('../../assets/catalog-thumbnails/wall/bunting-flags.png'),
  'imported-model-63': require('../../assets/catalog-thumbnails/seating/prayer-chair.png'),
  'imported-model-64': require('../../assets/catalog-thumbnails/prayer/minbars/minbar-variant-01-sand-teal-classic.png'),
  'imported-model-65': require('../../assets/catalog-thumbnails/prayer/minbars/minbar-variant-02-teal-rail.png'),
  'imported-model-66': require('../../assets/catalog-thumbnails/prayer/minbars/minbar-variant-03-terracotta-palace.png'),
  'imported-model-67': require('../../assets/catalog-thumbnails/prayer/minbars/minbar-variant-04-cream-square-canopy.png'),
  'imported-model-68': require('../../assets/catalog-thumbnails/prayer/minbars/minbar-variant-05-minimal-open.png'),
  'imported-model-69': require('../../assets/catalog-thumbnails/prayer/minbars/minbar-variant-06-scalloped-teal-canopy.png'),
  'imported-model-70': require('../../assets/catalog-thumbnails/prayer/minbars/minbar-variant-07-twin-arch-rail.png'),
  'imported-model-71': require('../../assets/catalog-thumbnails/prayer/minbars/minbar-variant-08-round-tower.png'),
  'imported-model-72': require('../../assets/catalog-thumbnails/prayer/minbars/minbar-variant-09-teal-panel.png'),
  'imported-model-73': require('../../assets/catalog-thumbnails/prayer/minbars/minbar-variant-10-minimal-sand-pavilion.png'),
  'imported-model-74': require('../../assets/catalog-thumbnails/prayer/prayer-rugs/prayer-rug-variant-01-terracotta-double-arch.png'),
  'imported-model-75': require('../../assets/catalog-thumbnails/prayer/prayer-rugs/prayer-rug-variant-02-sand-stepped-arch.png'),
  'imported-model-76': require('../../assets/catalog-thumbnails/prayer/prayer-rugs/prayer-rug-variant-03-teal-sunrise-arch.png'),
  'imported-model-77': require('../../assets/catalog-thumbnails/prayer/prayer-rugs/prayer-rug-variant-04-cream-terracotta-arch.png'),
  'imported-model-78': require('../../assets/catalog-thumbnails/prayer/prayer-rugs/prayer-rug-variant-05-teal-star-medallion.png'),
  'imported-model-79': require('../../assets/catalog-thumbnails/prayer/prayer-rugs/prayer-rug-variant-06-terracotta-nested-arches.png'),
  'imported-model-80': require('../../assets/catalog-thumbnails/prayer/prayer-rugs/prayer-rug-variant-07-sand-geometric-path.png'),
  'imported-model-81': require('../../assets/catalog-thumbnails/prayer/prayer-rugs/prayer-rug-variant-08-cream-scalloped-mihrab.png'),
  'imported-model-82': require('../../assets/catalog-thumbnails/prayer/prayer-rugs/prayer-rug-variant-09-teal-terracotta-corners.png'),
  'imported-model-83': require('../../assets/catalog-thumbnails/prayer/prayer-rugs/prayer-rug-variant-10-minimal-three-tone.png'),
  'imported-model-84': require('../../assets/catalog-thumbnails/prayer/tasbih/tasbih-01-midnight-onyx-gold.png'),
  'imported-model-85': require('../../assets/catalog-thumbnails/prayer/tasbih/tasbih-02-turquoise-silver.png'),
  'imported-model-86': require('../../assets/catalog-thumbnails/prayer/tasbih/tasbih-04-terracotta-heritage.png'),
  'imported-model-87': require('../../assets/catalog-thumbnails/prayer/tasbih/tasbih-05-sandalwood-cream.png'),
  'imported-model-88': require('../../assets/catalog-thumbnails/prayer/tasbih/tasbih-06-emerald-lantern.png'),
  'imported-model-89': require('../../assets/catalog-thumbnails/prayer/tasbih/tasbih-07-lavender-silver.png'),
  'imported-model-90': require('../../assets/catalog-thumbnails/prayer/tasbih/tasbih-08-rose-sand.png'),
  'imported-model-91': require('../../assets/catalog-thumbnails/prayer/tasbih/tasbih-10-festival-two-tone.png'),
  'imported-model-92': require('../../assets/catalog-thumbnails/prayer/rehal-quran/rehal-quran-variant-01-closed-teal-classic.png'),
  'imported-model-93': require('../../assets/catalog-thumbnails/prayer/rehal-quran/rehal-quran-variant-02-open-terracotta-inlay.png'),
  'imported-model-94': require('../../assets/catalog-thumbnails/prayer/rehal-quran/rehal-quran-variant-03-closed-terracotta-book.png'),
  'imported-model-95': require('../../assets/catalog-thumbnails/prayer/rehal-quran/rehal-quran-variant-05-closed-ivory-book.png'),
  'imported-model-96': require('../../assets/catalog-thumbnails/prayer/rehal-quran/rehal-quran-variant-06-open-teal-cover.png'),
  'imported-model-97': require('../../assets/catalog-thumbnails/prayer/rehal-quran/rehal-quran-variant-07-closed-sand-book.png'),
  'imported-model-98': require('../../assets/catalog-thumbnails/prayer/rehal-quran/rehal-quran-variant-08-open-scalloped-rehal.png'),
  'imported-model-99': require('../../assets/catalog-thumbnails/prayer/rehal-quran/rehal-quran-variant-09-open-minimal-gold.png'),
  'imported-model-100': require('../../assets/catalog-thumbnails/prayer/rehal-quran/rehal-quran-variant-10-closed-deep-teal.png'),
  'imported-model-101': require('../../assets/catalog-thumbnails/seating/majlis-cushions/majlis-cushion-variant-01-terracotta-classic-round.png'),
  'imported-model-102': require('../../assets/catalog-thumbnails/seating/majlis-cushions/majlis-cushion-variant-02-teal-radial-pouf.png'),
  'imported-model-103': require('../../assets/catalog-thumbnails/seating/majlis-cushions/majlis-cushion-variant-04-cream-petal-tuft.png'),
  'imported-model-104': require('../../assets/catalog-thumbnails/seating/majlis-cushions/majlis-cushion-variant-05-rounded-square.png'),
  'imported-model-105': require('../../assets/catalog-thumbnails/seating/majlis-cushions/majlis-cushion-variant-06-soft-oval.png'),
  'imported-model-106': require('../../assets/catalog-thumbnails/seating/majlis-cushions/majlis-cushion-variant-07-terracotta-segmented-pouf.png'),
  'imported-model-107': require('../../assets/catalog-thumbnails/seating/majlis-cushions/majlis-cushion-variant-08-scalloped-flower.png'),
  'imported-model-108': require('../../assets/catalog-thumbnails/seating/majlis-cushions/majlis-cushion-variant-09-teal-hexagonal-quilt.png'),
  'imported-model-109': require('../../assets/catalog-thumbnails/seating/majlis-cushions/majlis-cushion-variant-10-minimal-sand.png'),
};
